Natalya K: Homework_4 completed
eugene-okulik/Nataly.kamynina pull request #3
Opened 2024-10-17 03:55 UTC by NKamynina

2024-10-17 09:04 UTC, eugene-okulik requested changes
Как-то так вышло, что файл с заданием пустой )))  
Смотреть на файлы, который долетели в пулл реквест можно на вкладке "Files changed" в пулл реквесте.

2024-10-17 16:25 UTC, eugene-okulik requested changes
Всё отлично, но проверку на внимательность не прошла ))

2024-10-17 16:25 UTC, eugene-okulik commented on homework/natalya_kamynina/Homework_4/HW_4.py
> +my_dict['dict']['i am a tuple'] = '2'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-10-17 20:50 UTC, NKamynina commented on homework/natalya_kamynina/Homework_4/HW_4.py
> +my_dict['dict']['i am a tuple'] = '2'
хаха, блин, точно! Я поправила и отправила сново. Спасибо)

2024-10-18 08:23 UTC, eugene-okulik approved these changes

2024-10-18 08:23 UTC, merged