Natalya K: Homework 5 completed
eugene-okulik/Nataly.kamynina pull request #4
Opened 2024-10-22 02:39 UTC by NKamynina

Евгений привет, думаю Задание 2 сделала не правильно. Не совсем поняла как "С помощью срезов и метода index получите из каждой строки с результатом число".  Если все таки не правильно, дай плиз пример как это работает. Спасибо.

2024-10-22 08:50 UTC, eugene-okulik requested changes

2024-10-22 08:50 UTC, eugene-okulik commented on homework/natalya_kamynina/Homework_5/Task_2.py
В примерах - варианты того, как может ответить программа. Вместо числа 42 может оказаться число 28346473, вместо 514 число 3.   
Заморочка в том, чтобы найти в этой строке число, каким бы оно там ни было, а потом к этому числу добавить 10 и результат разспечатать. Для этого нужно найти в этих строках что-то одинаковое: количество символов перед числом разное; количество символов в числе тоже разное. Но есть в структуре всех строк что-то одинаковое и на это можно опереться. И вот когда ты сможешь написать код, который определяет с какого места в строке начинается число, можно будет его с помощью среза получить и использовать.  
Нам нужно сделать один код, который сможет работать с любым из вариантов ответа. То есть обработать каждую переменную абсолютно одинаковым кодом. Пока что делаем это копируя код, потом будем учиться как избежать здесь этого копирования.

2024-10-23 13:38 UTC, NKamynina commented on homework/natalya_kamynina/Homework_5/Task_2.py
Привет, переделалаб надеюсь, что сейчас поняла:)

2024-10-24 09:02 UTC, eugene-okulik requested changes

2024-10-24 09:02 UTC, eugene-okulik commented on homework/natalya_kamynina/Homework_5/Task_2.py
Давай еще попробуем. Сейчас ты добавляешь 10 к позиции пробела. Т.е. ты вычисляешь на какой позиции находится пробел и к этой позиции добавляешь 10.  
Но 10 нужно добавить к тому числу, которое идет после двоеточия. Т.е. нужно понять с какого места в строке начинается число. Это мы можем сделать узнав на какой позиции находится двоеточие. Число начинается через один символ после двоеточия. И вот тебе с помощью среза нужно взять из строки всё, что идет после двоеточия, преобразовать это в `int` и прибавить к этому 10.

2024-10-24 21:37 UTC, NKamynina commented
ну и еще раз посылаю задание Homework 5, Task №2 напроверку:)

2024-10-25 10:49 UTC, eugene-okulik requested changes

2024-10-25 10:49 UTC, eugene-okulik commented on homework/natalya_kamynina/Homework_5/Task_2.py
> +print(result)
А сейчас твой подход не универсален. Я уже писал, что это только примеры. Вместо числа 42 может оказаться число 3487346593845, и тогда твой код возьмет только число 45. Именно поэтому нужно не жестко прописать позицию, с которой начинается число, а вычислить эту позицию. Это мы можем сделать определив где находится двоеточие, так как во всех примерах число начинается после двоеточия. Схематично, было бы так
```python
aaa = 'результат операции: 42'
start_index = позиция двоеточия в этой строке
result_text = aaa[start_index:]
result_int = int(result_text)
result = result_int + 10
print(result)
```

2024-10-26 08:51 UTC, eugene-okulik approved these changes
Дааа!

2024-10-26 08:51 UTC, merged

2024-10-28 17:28 UTC, NKamynina commented
ура !!!!